### ISSUE TITLE
Argument "message" for method "notification" must be unicode or str

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/script.episodeHunter#24]
Some users encounter this error:

```
ERROR: EXCEPTION: argument "message" for method "notification" must be unicode or str
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.TypeError'>
  Error Contents: argument "message" for method "notification" must be unicode or str
  Traceback (most recent call last):
  File "addon.py", line 8, in <module>
  player.run()
    File "resources/lib/eh_player.py", line 65, in run
    self.watching()
      File "resources/lib/eh_player.py", line 166, in watching
      percent=int(100 * self.__watched_time / self.__total_time)
        File "resources/lib/eh_player.py", line 223, in communicate_with_eh
        dialog.create_notification(error.value)
          File "resources/lib/gui/dialog.py", line 27, in create_notification
          dialog.notification(config.__NAME__, message,  settings.getAddonInfo("icon"), 5000)
            TypeError: argument "message" for method "notification" must be unicode or str
-->End of Python script error report<--
```

Investigate why.

**Comment by tjoskar** [comment]
Related: #23
